// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef execpk_h
#define execpk_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *main_window;
#include <FL/Fl_Box.H>
#include <FL/Fl_Secret_Input.H>
extern Fl_Secret_Input *input_fl;
#include <FL/Fl_Button.H>
#include <FL/Fl_Output.H>
extern Fl_Output *cmd_op;
void CB_Button(Fl_Widget*, void*);
void Exit_button(Fl_Widget*, void*);
#endif
